export default {
  calf: require('../../assets/icons/calf-female.png'),
  calves: require('../../assets/icons/calves.png'),
  calfMale: require('../../assets/icons/calf.png'),
  steer: require('../../assets/icons/bull-facing-right.png'),
  steers: require('../../assets/icons/steers.png'),

  weaner: require('../../assets/icons/cow-silhouette-female.png'),
  weaners: require('../../assets/icons/weaners.png'),
  weanerMale: require('../../assets/icons/cow-silhouette.png'),
  heifer: require('../../assets/icons/cow2.png'),
  heifers: require('../../assets/icons/heifers.png'),
  bull: require('../../assets/icons/bull-facing-right1.png'),
  bulls: require('../../assets/icons/bulls.png'),
  cow: require('../../assets/icons/cow21.png'),
  cows: require('../../assets/icons/cowsMenu.png'),
  event: require('../../assets/icons/calendar.png'),
  convert: require('../../assets/icons/convert.png'),
  milk: require('../../assets/icons/feeding-bottle.png'),
  castration: require('../../assets/icons/castration.png'),
  vaccine: require('../../assets/icons/vaccine.png'),
  other: require('../../assets/icons/other.png'),
  dryoff: require('../../assets/icons/dryoff.png'),
  dryoffs: require('../../assets/icons/dryoffs.png'),
  lactating: require('../../assets/icons/lactating.png'),
  insemination: require('../../assets/icons/insemination.png'),
  childbirth: require('../../assets/icons/childbirth.png'),
  pregnancyTest: require('../../assets/icons/pregnancy-test.png'),
  pregnanc: require('../../assets/icons/pregnanc.png'),
  abortedPregnancy: require('../../assets/icons/abortedchildbirth.png'),
  unarchive: require('../../assets/icons/unarchive.png'),
  status: require('../../assets/icons/clock.png'),
  logo: require('../../assets/icon.png'),
  vip: require('../../assets/crown.png'),
};
