export default {
  BREEDERSINFO: 'BreedersInfo',
  GROUPSINFO: 'GroupsInfo',
  LOGININFO: 'LoginInfo',
  LOGIN: 'SignIn',
  REGISTER: 'SignUp',
  FORGOT_PASSWORD: 'ForgotPassword',
  VERIFY: 'Verify',
  HOME: 'Home',
  HOME_DRAWER: 'Home Drawer',
  ADD_EDIT_CATTELE: 'AddEditCattele',
  ADD_EDIT_Milk: 'AddEditMilk',
  CATTELE: 'Cattele',
  CATTELE_TAB: 'Cattele_Tab',
  TRANSACTIONS: 'Transactions',
  MILKRECORD: 'Milk Record',
  EVENTS: 'Events',
  Learning: 'Learning',
  SETTING: 'Setting',
  ABOUT: 'About',
  SUPPORT: 'Support',

  SALON: 'Salon',
  FLOCK: 'Flock',
  FLOCKTIP: 'FlockTip',
  BREED: 'BREED',
  VIEWRECORD: 'ViewRecord',
  VIEWRECORDTAB: 'ViewRecordTab',
  ADDEVENTS: 'AddEvents',
  PAYMENT: 'Payment',
};
